spring:
  application:
    name: story_helper_back
  data:
    cassandra:
      contact-points: 127.0.0.1:9042
      keyspace-name: story_helper
      local-datacenter: datacenter1

server:
  port: 8090
  servlet:
    context-path: /story_helper_back

auth:
  check:
    url: http://localhost:8080/story_helper_auth/token/check

